In [41]:
import pickle
from text_process import text_preprocess
from utils import *
import json
import numpy as np
import os

<h5>Load model</h5>

In [42]:
lda_model = pickle.load(open('./ldamodel.pkl', 'rb'))
lda_model.print_topics(num_topics=40, num_words=50)

[(0,
  '0.335*"nữ" + 0.127*"wiliams" + 0.074*"lợi_thế" + 0.058*"david" + 0.029*"john" + 0.027*"lopez" + 0.027*"u" + 0.024*"james" + 0.023*"paul" + 0.019*"de" + 0.018*"son" + 0.016*"dẫn_đầu" + 0.013*"martin" + 0.013*"kết_hôn" + 0.008*"blue" + 0.007*"khoẻ_mạnh" + 0.007*"bản_chất" + 0.005*"chúa" + 0.005*"marc" + 0.005*"mtv" + 0.004*"phái" + 0.004*"steven" + 0.004*"jon" + 0.003*"man" + 0.003*"robert" + 0.003*"brian" + 0.003*"sped" + 0.002*"ireland" + 0.002*"giáng" + 0.002*"logo" + 0.002*"anthony" + 0.002*"ông_hoàng" + 0.001*"ngoạn_mục" + 0.001*"who" + 0.001*"huỷ" + 0.001*"danh_sách" + 0.001*"ngôi_sao" + 0.001*"j" + 0.001*"xếp" + 0.001*"bầu" + 0.000*"hâm_mộ" + 0.000*"giành" + 0.000*"hai" + 0.000*"duf" + 0.000*"đột_phá" + 0.000*"philipines" + 0.000*"kết_quả" + 0.000*"vị" + 0.000*"dublin" + 0.000*"nổi_bật"'),
 (1,
  '0.027*"đi" + 0.016*"độ" + 0.012*"đường" + 0.011*"đất" + 0.010*"lọt" + 0.010*"đầu" + 0.010*"đánh_bóng" + 0.010*"lớp" + 0.009*"hai" + 0.008*"tiếng" + 0.008*"dây" + 0.008*"mặt" + 0.

<h5>Load các bài viết cho người dùng</h5>

In [43]:
posts = []
path = "../python crawl/24hData"
for filename in os.listdir(path):
   with open(os.path.join(path, filename), 'r', encoding='utf-8') as f:
            # text = f.read()
            text = text_preprocess(f.read())
            posts.append(text)

In [44]:
dict = pickle.load(open('./dict.pkl', 'rb'))
doc_term_matrix_suggest = [dict.doc2bow(i) for i in posts]
count = 0

post_favor = []

for i in lda_model[doc_term_matrix_suggest]:
    tmp= [0] * 40
    for j in i[0]:
        tmp[j[0]] = j[1]
    count += 1
    post_favor.append(tmp)
post_favor[0]

[0,
 0.061997708,
 0,
 0.011230293,
 0,
 0,
 0,
 0,
 0.033669833,
 0,
 0.023808623,
 0.20391256,
 0,
 0.035357375,
 0,
 0.058164816,
 0.01140464,
 0,
 0,
 0,
 0.14638953,
 0,
 0,
 0,
 0,
 0,
 0,
 0.010738902,
 0,
 0,
 0,
 0,
 0.02266713,
 0,
 0.26198253,
 0.01826832,
 0,
 0.044999376,
 0,
 0]

<h5>Ma trận người dùng - chủ đề</h5>

In [45]:
user_views_count = []
userJson = open('./user.json',"r")
user = json.loads(userJson.read())
for key, value in user['topic-list'].items():
    user_views_count.append(value)

user_views = convertIntArrayToPercentArray(user_views_count)
    
user_topic_mtrx = np.array(user_views)
user_topic_mtrx

array([0.01298701, 0.004329  , 0.02164502, 0.02597403, 0.21645022,
       0.00865801, 0.        , 0.004329  , 0.03896104, 0.06926407,
       0.01298701, 0.        , 0.        , 0.        , 0.        ,
       0.38961039, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.01298701, 0.        , 0.004329  , 0.        ,
       0.        , 0.08658009, 0.        , 0.        , 0.        ,
       0.        , 0.03896104, 0.        , 0.        , 0.03030303,
       0.        , 0.        , 0.02164502, 0.        , 0.        ])

<h5>Ma trận chủ đề - bài viết</h5>

In [46]:
topic_post_mtrx = np.array(post_favor).T
topic_post_mtrx

array([[0.        , 0.        , 0.        , ..., 0.01705619, 0.        ,
        0.01075059],
       [0.06199771, 0.05953563, 0.217658  , ..., 0.07860436, 0.07081473,
        0.16279066],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.04499938, 0.01430953, 0.03139284, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.05287263, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

<h5>Ma trận người dùng - bài viết</h5>

In [47]:
user_post_matrx = np.matmul(user_topic_mtrx, topic_post_mtrx)
user_post_matrx

array([0.03375559, 0.03156721, 0.02774886, 0.0142667 , 0.02803295,
       0.0208683 , 0.0216124 , 0.00901678, 0.01769055, 0.01976985,
       0.03030344, 0.01672999, 0.02091873, 0.04808866, 0.02346125,
       0.03579646, 0.01327691, 0.01159875, 0.03162426, 0.02368207,
       0.00838336, 0.01725126, 0.03079217, 0.03870958, 0.05814498,
       0.0321611 , 0.01473197, 0.02591031, 0.04474188, 0.02404533,
       0.03325405, 0.01951102, 0.05158965, 0.06035435, 0.01951042,
       0.01803781, 0.04550954, 0.03438187, 0.03069193, 0.04776657,
       0.03995165, 0.03256657, 0.02643088, 0.02010201, 0.01867371,
       0.0277219 , 0.06771537, 0.02993407, 0.02740194, 0.02951867,
       0.04102482, 0.03478418, 0.03638019, 0.03891242, 0.0184207 ,
       0.07297031, 0.0551177 , 0.05222088, 0.02457892, 0.03162617,
       0.03311434, 0.02877652, 0.02593084, 0.03291997, 0.03102745,
       0.04553208, 0.03208646, 0.04394071, 0.01980791, 0.01615329,
       0.03102257, 0.01996213, 0.01343441, 0.02277602, 0.08809

<h5>Thứ tự ranking các bài viết</h5>

In [48]:
user_post_dict = ConvertListToDict(user_post_matrx)
user_post_dict_sorted = sorted(user_post_dict, key=user_post_dict.get, reverse= True)
user_post_dict_sorted

[74,
 113,
 55,
 46,
 92,
 76,
 33,
 24,
 56,
 110,
 57,
 32,
 98,
 13,
 39,
 65,
 36,
 79,
 28,
 112,
 67,
 80,
 77,
 50,
 40,
 53,
 23,
 78,
 95,
 52,
 15,
 85,
 51,
 37,
 0,
 30,
 60,
 63,
 41,
 100,
 25,
 66,
 59,
 18,
 1,
 64,
 70,
 90,
 97,
 22,
 93,
 38,
 10,
 47,
 104,
 49,
 94,
 88,
 121,
 61,
 102,
 4,
 122,
 2,
 45,
 115,
 48,
 105,
 91,
 87,
 117,
 42,
 62,
 27,
 58,
 99,
 89,
 123,
 106,
 29,
 19,
 14,
 73,
 108,
 116,
 86,
 82,
 6,
 101,
 12,
 5,
 84,
 43,
 71,
 68,
 9,
 83,
 31,
 34,
 107,
 119,
 44,
 54,
 111,
 35,
 8,
 21,
 81,
 120,
 11,
 103,
 75,
 69,
 96,
 118,
 26,
 3,
 72,
 16,
 114,
 17,
 7,
 20,
 109]

<h5>Hiển thị các link bài viết cho người dùng</h5>

In [49]:
path = "../python crawl/24hUrls.txt"
urlsFile = open(path, 'r')
links = urlsFile.readlines()
for index in user_post_dict_sorted:
    print(links[index])

https://www.24h.com.vn/giao-duc-du-hoc/me-bat-con-gai-22-tuoi-kiem-tra-nong-do-con-khi-di-choi-ve-cac-bac-phu-huynh-nghi-gi-c216a1373521.html

https://www.24h.com.vn/phi-thuong-ky-quac/kiem-bon-tien-nho-so-huu-bo-nguc-tu-nhien-khung-nhat-the-gioi-c159a1048665.html

https://www.24h.com.vn/giao-duc-du-hoc/thu-tai-doan-xem-day-la-mui-cua-loai-dong-vat-nao-c216a1360627.html

https://www.24h.com.vn/the-thao/video-tennis-alcaraz-otte-chien-thang-chong-vanh-den-gan-djokovic-wimbledon-c101a1374020.html

https://www.24h.com.vn/xe-may-xe-dap/gia-xe-dap-dien-osakar-moi-nhat-trong-thang-07-2022-c748a1373764.html

https://www.24h.com.vn/phi-thuong-ky-quac/thay-con-gai-roi-khoi-ghe-sofa-ong-bo-cuu-nguy-trong-gang-tac-khien-dan-mang-khen-ngoi-c159a1374331.html

https://www.24h.com.vn/the-gioi-cong-nghe/tin-hieu-cua-nguoi-dung-khi-co-thong-tin-vertu-sap-duoc-phan-phoi-chinh-thuc-tai-viet-nam-c674a1368862.html

https://www.24h.com.vn/bong-da/chu-nha-world-cup-2022-bat-ngo-cam-chuyen-ay-nguy-co-ngoi-tu-