In [1]:
import pickle
from text_process import text_preprocess
from utils import *
import json
import numpy as np
import os

<h5>Load model</h5>

In [2]:
lda_model = pickle.load(open('./ldamodel.pkl', 'rb'))
lda_model.print_topics(num_topics=40, num_words=50)

[(0,
  '0.172*"thư" + 0.110*"phát_hành" + 0.057*"bọn" + 0.051*"q" + 0.045*"cd" + 0.045*"cháu" + 0.030*"hôn" + 0.026*"giả" + 0.025*"bền" + 0.023*"du" + 0.022*"kết_hôn" + 0.019*"gửi" + 0.019*"sắc_màu" + 0.019*"xin_lỗi" + 0.019*"go" + 0.018*"chân_thành" + 0.017*"khanh" + 0.012*"email" + 0.008*"chín_chắn" + 0.008*"nổi_trội" + 0.008*"đối_lập" + 0.007*"nghi_ngờ" + 0.006*"góp_ý" + 0.004*"non_nớt" + 0.003*"chuyển_mình" + 0.003*"xúc_tác" + 0.002*"suy_nghĩ_lại" + 0.002*"dày_dạn" + 0.002*"bảo" + 0.002*"ngất_ngây" + 0.001*"họp_mặt" + 0.001*"xôn_xao" + 0.001*"biểu_hiện" + 0.001*"cần_thơ" + 0.001*"thiết_kế" + 0.001*"con_nuôi" + 0.001*"quy_luật" + 0.001*"ảnh" + 0.000*"xích_mích" + 0.000*"trẻ_con" + 0.000*"mây" + 0.000*"tâm" + 0.000*"mẫu" + 0.000*"đón_nhận" + 0.000*"hình_ảnh" + 0.000*"dấu" + 0.000*"viết" + 0.000*"tham_gia" + 0.000*"thăng" + 0.000*"thành_tích"'),
 (1,
  '0.198*"tp" + 0.190*"hcm" + 0.116*"minh" + 0.064*"huỳnh" + 0.044*"hồng" + 0.032*"hùng" + 0.031*"sở" + 0.031*"nguyễn" + 0.030*"h" + 0.0

<h5>Load các bài viết cho người dùng</h5>

In [3]:
posts = []
path = "../python crawl/24hData"
for filename in os.listdir(path):
   with open(os.path.join(path, filename), 'r', encoding='utf-8') as f:
            # text = f.read()
            text = text_preprocess(f.read())
            posts.append(text)

In [4]:
dict = pickle.load(open('./dict.pkl', 'rb'))
doc_term_matrix_suggest = [dict.doc2bow(i) for i in posts]
count = 0

post_favor = []

for i in lda_model[doc_term_matrix_suggest]:
    tmp= [0] * 40
    for j in i[0]:
        tmp[j[0]] = j[1]
    count += 1
    post_favor.append(tmp)
post_favor[0]

[0,
 0.13720329,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0.011651814,
 0,
 0.026103655,
 0,
 0.022010097,
 0,
 0,
 0.013012729,
 0,
 0.06416294,
 0,
 0,
 0.06779775,
 0.040078778,
 0,
 0,
 0.13483797,
 0,
 0,
 0.015884286,
 0.072489455,
 0.05520969,
 0,
 0,
 0.03152487,
 0.023396377,
 0.22985026,
 0,
 0.010627288,
 0,
 0]

<h5>Ma trận người dùng - chủ đề</h5>

In [5]:
user_views_count = []
userJson = open('./user.json',"r")
user = json.loads(userJson.read())
for key, value in user['topic-list'].items():
    user_views_count.append(value)

user_views = convertIntArrayToPercentArray(user_views_count)
    
user_topic_mtrx = np.array(user_views)
user_topic_mtrx

array([0.01298701, 0.004329  , 0.02164502, 0.02597403, 0.21645022,
       0.00865801, 0.        , 0.004329  , 0.03896104, 0.06926407,
       0.01298701, 0.        , 0.        , 0.        , 0.        ,
       0.38961039, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.01298701, 0.        , 0.004329  , 0.        ,
       0.        , 0.08658009, 0.        , 0.        , 0.        ,
       0.        , 0.03896104, 0.        , 0.        , 0.03030303,
       0.        , 0.        , 0.02164502, 0.        , 0.        ])

<h5>Ma trận chủ đề - bài viết</h5>

In [6]:
topic_post_mtrx = np.array(post_favor).T
topic_post_mtrx

array([[0.        , 0.        , 0.02126455, ..., 0.01282526, 0.        ,
        0.        ],
       [0.13720329, 0.1208066 , 0.0146642 , ..., 0.02933849, 0.02605785,
        0.02547731],
       [0.        , 0.        , 0.01331929, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.01062729, 0.        , 0.04757832, ..., 0.        , 0.0191405 ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

<h5>Ma trận người dùng - bài viết</h5>

In [12]:
user_post_matrx = np.matmul(user_topic_mtrx, topic_post_mtrx)
user_post_matrx

array([0.0032205 , 0.00293868, 0.01687883, 0.00393543, 0.00933474,
       0.00442194, 0.00523837, 0.0167016 , 0.01452524, 0.00877944,
       0.00861866, 0.01509259, 0.00943858, 0.00687224, 0.00931604,
       0.00222372, 0.00771872, 0.00629371, 0.00843654, 0.00472531,
       0.00645573, 0.00409294, 0.00538086, 0.00463328, 0.00590287,
       0.00658869, 0.01505242, 0.00475905, 0.01150218, 0.0074943 ,
       0.02123057, 0.02587181, 0.00934794, 0.0098283 , 0.02586556,
       0.00850626, 0.0174742 , 0.0041985 , 0.00903821, 0.01109055,
       0.00689282, 0.00824912, 0.0055771 , 0.02065416, 0.00571578,
       0.00802774, 0.00258588, 0.00200626, 0.00614325, 0.00563894,
       0.00638845, 0.00794327, 0.00317045, 0.01357991, 0.00539903,
       0.01306539, 0.00887866, 0.0066799 , 0.00350326, 0.01286449,
       0.01387135, 0.00430403, 0.00950093, 0.00872861, 0.00570339,
       0.01089132, 0.00380932, 0.00658098, 0.00597863, 0.00456962,
       0.00406706, 0.01017647, 0.01117223, 0.00556005, 0.00284

<h5>Thứ tự ranking các bài viết</h5>

In [8]:
user_post_dict = ConvertListToDict(user_post_matrx)
user_post_dict_sorted = sorted(user_post_dict, key=user_post_dict.get, reverse= True)
user_post_dict_sorted

[31,
 34,
 100,
 30,
 78,
 43,
 112,
 36,
 2,
 7,
 87,
 83,
 11,
 26,
 8,
 60,
 53,
 99,
 55,
 84,
 59,
 85,
 86,
 106,
 28,
 72,
 39,
 89,
 65,
 104,
 90,
 108,
 105,
 71,
 110,
 33,
 123,
 62,
 12,
 32,
 4,
 14,
 97,
 75,
 38,
 56,
 9,
 63,
 10,
 111,
 35,
 109,
 18,
 103,
 92,
 41,
 107,
 45,
 51,
 91,
 16,
 77,
 119,
 29,
 102,
 40,
 13,
 81,
 57,
 25,
 67,
 20,
 50,
 17,
 121,
 48,
 68,
 101,
 24,
 113,
 79,
 118,
 44,
 64,
 49,
 42,
 73,
 54,
 22,
 122,
 6,
 76,
 114,
 27,
 19,
 23,
 69,
 5,
 94,
 61,
 37,
 88,
 21,
 70,
 115,
 3,
 80,
 66,
 117,
 82,
 58,
 93,
 116,
 0,
 52,
 98,
 1,
 74,
 46,
 120,
 15,
 96,
 47,
 95]

<h5>Hiển thị các link bài viết cho người dùng</h5>

In [9]:
path = "../python crawl/24hUrls.txt"
urlsFile = open(path, 'r')
links = urlsFile.readlines()
for index in user_post_dict_sorted:
    print(links[index])

https://www.24h.com.vn/thoi-trang-hi-tech/video-so-sanh-chi-tiet-macbook-pro-13-inch-m2-va-m1-c407a1373196.html

https://www.24h.com.vn/the-gioi-cong-nghe/big-sale-khung-nhat-nam-topzone-ban-iphone-13-chi-nua-gia-loat-san-pham-apple-giam-manh-den-20-c674a1368891.html

https://www.24h.com.vn/doi-song-showbiz/trum-giang-ho-phim-nguoi-phan-xu-giai-nghe-gay-tiec-nuoi-tuoi-u60-nuoi-con-mon-c729a1351208.html

https://www.24h.com.vn/thoi-trang-hi-tech/-2022-se-ap-dung-cong-nghe-bat-viet-vi-moi-c407a1374274.html

https://www.24h.com.vn/phi-thuong-ky-quac/video-giat-minh-chung-kien-khoanh-khac-nguoi-phu-nu-bi-cua-kinh-roi-trung-dau-c159a1306960.html

https://www.24h.com.vn/o-to/gia-xe-honda-city-niem-yet-va-lan-banh-thang-7-2022-c747a1375028.html

https://www.24h.com.vn/giao-duc-du-hoc/dat-phep-tinh-voi-8-so-8-ban-co-tim-duoc-cach-giai-khong-c216a1346030.html

https://www.24h.com.vn/tin-tuc-trong-ngay/chot-thoi-diem-thu-phi-rac-thai-sinh-hoat-theo-kg-c46a1200088.html

https://www.24h.com.vn/tin