In [1]:
import pickle
from text_process import text_preprocess
from utils import *
import json
import numpy as np
import os

In [ ]:
lda_model = pickle.load(open('./ldamodel.pkl', 'rb'))
lda_model.print_topics(num_topics=40, num_words=50)

In [3]:
posts = []
path = "../python crawl/24hData"
for filename in os.listdir(path):
   with open(os.path.join(path, filename), 'r', encoding='utf-8') as f:
            # text = f.read()
            text = text_preprocess(f.read())
            posts.append(text)

In [ ]:
dict = pickle.load(open('./dict.pkl', 'rb'))
doc_term_matrix_suggest = [dict.doc2bow(i) for i in posts]
count = 0

post_favor = []

for i in lda_model[doc_term_matrix_suggest]:
    tmp= [0] * 40
    for j in i[0]:
        tmp[j[0]] = j[1]
    count += 1
    post_favor.append(tmp)
post_favor[0]

In [5]:
user_views_count = []
userJson = open('./user.json',"r")
user = json.loads(userJson.read())
for key, value in user['topic-list'].items():
    user_views_count.append(value)

user_views = convertIntArrayToPercentArray(user_views_count)
    
user_favor_mtrx = np.array(user_views)
user_favor_mtrx

array([0.02205882, 0.00735294, 0.03676471, 0.04411765, 0.73529412,
       0.01470588, 0.        , 0.00735294, 0.06617647, 0.04411765,
       0.02205882, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [6]:
favor_post_mtrx = np.array(post_favor).T
favor_post_mtrx

array([[0.        , 0.        , 0.        , ..., 0.03999692, 0.0158196 ,
        0.        ],
       [0.06199771, 0.05953563, 0.217658  , ..., 0.07101107, 0.14450641,
        0.10253727],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.04499938, 0.01430953, 0.03139284, ..., 0.        , 0.        ,
        0.02885423],
       [0.        , 0.        , 0.05287263, ..., 0.01997563, 0.        ,
        0.0121302 ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.0155495 ,
        0.01228412]])

In [7]:
user_post_matrx = np.matmul(user_favor_mtrx, favor_post_mtrx)
user_post_matrx

array([0.00370466, 0.00341118, 0.0216148 , 0.01918012, 0.00507786,
       0.00503469, 0.01576748, 0.03011354, 0.01047488, 0.07369013,
       0.03011393, 0.01144662, 0.09348505, 0.06379954, 0.01854267,
       0.0429962 , 0.00872675, 0.00839445, 0.00701446, 0.03728119,
       0.0323411 , 0.03492242, 0.02666837, 0.04832786, 0.03306968,
       0.04801528, 0.06626914, 0.02846102, 0.02943103, 0.02376272,
       0.02676734, 0.01538457, 0.03629785, 0.00832638, 0.00904567,
       0.01437611, 0.00756862, 0.02395275, 0.0205283 , 0.03178952,
       0.05686593, 0.07521546, 0.00682582, 0.03296786, 0.00692425,
       0.0075996 , 0.00629474, 0.00597832, 0.00417531, 0.03633456,
       0.00764895, 0.01126969, 0.03943454, 0.00565526, 0.00779056,
       0.00740954])

In [8]:
user_post_dict = ConvertListToDict(user_post_matrx)
user_post_dict_sorted = sorted(user_post_dict, key=user_post_dict.get, reverse= True)
user_post_dict_sorted

[12,
 41,
 9,
 26,
 13,
 40,
 23,
 25,
 15,
 52,
 19,
 49,
 32,
 21,
 24,
 43,
 20,
 39,
 10,
 7,
 28,
 27,
 30,
 22,
 37,
 29,
 2,
 38,
 3,
 14,
 6,
 31,
 35,
 11,
 51,
 8,
 34,
 16,
 17,
 33,
 54,
 50,
 45,
 36,
 55,
 18,
 44,
 42,
 46,
 47,
 53,
 4,
 5,
 48,
 0,
 1]

In [18]:
urlsFile = open('../python crawl/24hUrls.txt','r',encoding='utf-8')
urls = urlsFile.readlines()
for i in user_post_dict_sorted:
    print("link in line "+ " " + str(i+1) + ": " + urls[i])


link in line  13: https://www.24h.com.vn/du-lich-24h/kham-pha-phuong-hoang-co-tran-xinh-dep-tru-danh-trung-hoa-c76a1345437.html

link in line  42: https://www.24h.com.vn/media-24h/4-bi-quyet-song-de-tranh-ung-thu-cai-thien-tuoi-tho-c762a1375193.html

link in line  10: https://www.24h.com.vn/du-lich-24h/cay-cau-uon-luon-nhu-song-nuoc-giua-nui-rung-cu-ngo-la-san-pham-cua-photoshop-c76a1368498.html

link in line  27: https://www.24h.com.vn/bong-da/sep-lon-barcelona-dau-hang-thuong-vu-lewandowski-chelsea-mung-tham-c48a1374134.html

link in line  14: https://www.24h.com.vn/giao-duc-du-hoc/khi-bi-cha-me-mang-tre-im-lang-hay-noi-lai-cho-thay-chung-co-nhung-tinh-cach-nay-khi-lon-len-c216a1372651.html

link in line  41: https://www.24h.com.vn/tin-tuc-trong-ngay/hinh-hai-duong-vanh-dai-2-truoc-khi-hop-long-nhip-cuoi-o-ha-noi-c46a1371804.html

link in line  24: https://www.24h.com.vn/bong-da/nguoi-dac-biet-ligue-1-gia-nhap-psg-tuyen-bo-dan-mat-messi-mbappe-neymar-c48a1375086.html

link in line  2